namespace Codelet.Testing.AutoFixture
{
  using Ploeh.AutoFixture;
  using Ploeh.AutoFixture.AutoMoq;
  using Ploeh.AutoFixture.Xunit2;

  /// <summary>
  /// Provides auto-generated data specimens generated by AutoFixture using Moq
  ///  as an extension to xUnit.net's Theory attribute.
  /// </summary>
  public class AutoMoqDataAttribute : AutoDataAttribute
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="AutoMoqDataAttribute"/> class.
    /// </summary>
    public AutoMoqDataAttribute()
      : base(new Fixture().Customize(new AutoConfiguredMoqCustomization()))
    {
    }
  }
}