namespace Codelet.Testing.AutoFixture
{
  using Ploeh.AutoFixture.Xunit2;

  /// <summary>
  /// Provides a data source for a data theory, with the data coming from inline values
  /// combined with auto-generated data specimens generated by AutoFixture using Moq.
  /// </summary>
  public class InlineAutoMoqDataAttribute : InlineAutoDataAttribute
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="InlineAutoMoqDataAttribute"/> class.
    /// </summary>
    /// <param name="values">The data values to pass to the theory.</param>
    public InlineAutoMoqDataAttribute(params object[] values)
      : base(new AutoMoqDataAttribute(), values)
    {
    }
  }
}