namespace Codelet.Testing.AutoFixture
{
  using System;
  using System.Collections.Generic;
  using System.Linq;
  using System.Reflection;
  using global::AutoFixture.Xunit2;
  using Xunit;
  using Xunit.Sdk;

  /// <summary>
  /// Provides a data source for a data theory, with the data coming from the given member source
  /// combined with auto-generated data specimens generated by AutoFixture.
  /// </summary>
  public class MemberAutoDataAttribute : DataAttribute
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="MemberAutoDataAttribute"/> class.
    /// </summary>
    /// <param name="memberName">Name of the member.</param>
    /// <param name="parameters">The parameters.</param>
    public MemberAutoDataAttribute(string memberName, params object[] parameters)
      : this(memberName, parameters, new AutoDataAttribute())
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="MemberAutoDataAttribute"/> class.
    /// </summary>
    /// <param name="memberName">Name of the member.</param>
    /// <param name="parameters">The parameters.</param>
    /// <param name="autoDataAttribute">The automatic data attribute.</param>
    protected MemberAutoDataAttribute(string memberName, object[] parameters, AutoDataAttribute autoDataAttribute)
    {
      this.MemberDataAttribute = new MemberDataAttribute(memberName, parameters);
      this.AutoDataAttribute = autoDataAttribute;
    }

    /// <summary>
    /// Gets or sets the type of the member.
    /// </summary>
    public Type MemberType
    {
      get => this.MemberDataAttribute.MemberType;
      set => this.MemberDataAttribute.MemberType = value;
    }

    private MemberDataAttribute MemberDataAttribute { get; }

    private AutoDataAttribute AutoDataAttribute { get; }

    /// <inheritdoc />
    public override IEnumerable<object[]> GetData(MethodInfo testMethod)
      => this
      .MemberDataAttribute
      .GetData(testMethod)
      .Select(memberDataSet =>
        new CompositeDataAttribute(new InlineDataAttribute(memberDataSet), this.AutoDataAttribute)
        .GetData(testMethod)
        .First());
  }
}