namespace Codelet.Testing.AutoFixture
{
  /// <summary>
  /// Provides a data source for a data theory, with the data coming from the given member source
  /// combined with auto-generated data specimens generated by AutoFixture using Moq.
  /// </summary>
  public class MemberAutoMoqDataAttribute : MemberAutoDataAttribute
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="MemberAutoMoqDataAttribute"/> class.
    /// </summary>
    /// <param name="memberName">Name of the member.</param>
    /// <param name="parameters">The parameters.</param>
    public MemberAutoMoqDataAttribute(string memberName, params object[] parameters)
      : base(memberName, parameters, new AutoMoqDataAttribute())
    {
    }
  }
}